# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pi\"0\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\r\n\x05ratio\x18\x02 \x01(\x02\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\" \n\rImageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x0f\x46ilenameRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x10\x46ilenameResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t2\xbf\x01\n\x03\x41pi\x12\x37\n\x0bUploadImage\x12\x12.api.UploadRequest\x1a\x12.api.ImageResponse\"\x00\x12;\n\rDownloadImage\x12\x14.api.DownloadRequest\x1a\x12.api.ImageResponse\"\x00\x12\x42\n\x0fPrintSavedFiles\x12\x14.api.FilenameRequest\x1a\x15.api.FilenameResponse\"\x00\x30\x01\x62\x06proto3')



_UPLOADREQUEST = DESCRIPTOR.message_types_by_name['UploadRequest']
_DOWNLOADREQUEST = DESCRIPTOR.message_types_by_name['DownloadRequest']
_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
_FILENAMEREQUEST = DESCRIPTOR.message_types_by_name['FilenameRequest']
_FILENAMERESPONSE = DESCRIPTOR.message_types_by_name['FilenameResponse']
UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQUEST,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:api.UploadRequest)
  })
_sym_db.RegisterMessage(UploadRequest)

DownloadRequest = _reflection.GeneratedProtocolMessageType('DownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADREQUEST,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:api.DownloadRequest)
  })
_sym_db.RegisterMessage(DownloadRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:api.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

FilenameRequest = _reflection.GeneratedProtocolMessageType('FilenameRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILENAMEREQUEST,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:api.FilenameRequest)
  })
_sym_db.RegisterMessage(FilenameRequest)

FilenameResponse = _reflection.GeneratedProtocolMessageType('FilenameResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILENAMERESPONSE,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:api.FilenameResponse)
  })
_sym_db.RegisterMessage(FilenameResponse)

_API = DESCRIPTOR.services_by_name['Api']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPLOADREQUEST._serialized_start=18
  _UPLOADREQUEST._serialized_end=66
  _DOWNLOADREQUEST._serialized_start=68
  _DOWNLOADREQUEST._serialized_end=103
  _IMAGERESPONSE._serialized_start=105
  _IMAGERESPONSE._serialized_end=137
  _FILENAMEREQUEST._serialized_start=139
  _FILENAMEREQUEST._serialized_end=173
  _FILENAMERESPONSE._serialized_start=175
  _FILENAMERESPONSE._serialized_end=211
  _API._serialized_start=214
  _API._serialized_end=405
# @@protoc_insertion_point(module_scope)
